# Generated by Django 3.0.5 on 2020-04-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='join_date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
